language: cpp
env: SOURCE_JDK_TAG=demo0.0.1
matrix:
  include:
  - os: windows
    env: OS_BUILD=windows
    before_install:
    - choco install cygwin
    - C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip
before_script:
  - if [[ $OS_BUILD == "windows" ]]; then
      git config --system core.longpaths true;
      git config --global core.autocrlf false;
    fi
  - unset -v _JAVA_OPTIONS;
  - git clone --depth 1 https://github.com/TravaOpenJDK/openjdk-build.git;
script:
  - export JDK_BOOT_DIR="$PWD/openjdk-build/jdk-10"
  - export HSWAP_AGENT_DOWNLOAD_URL=https://github.com/n9x0n/HotswapAgent/releases/download/1.3.1.1/hotswap-agent-1.3.1.1-SNAPSHOT.jar
  - mkdir -p "$JDK_BOOT_DIR"
  - if [[ $OS_BUILD == "windows" ]]; then
      powershell -Command "C:\tools\cygwin\bin\bash.exe -c './build_windows.sh'";
    fi
deploy:
  provider: releases
  api_key:
    secure: $API_KEY
  file_glob: true
  file: openjdk-build/workspace/target/*
  skip_cleanup: true
  on:
    repo: n9x0n/trava-jdk-11-dcevm
    all_branches: true
    tags: true
