language: cpp
env: SOURCE_JDK_TAG=dcevm-11.0.1+8 
matrix:
  include:
  - os: osx
    env: OS_BUILD=osx
  - os: linux
    env: OS_BUILD=linux
    dist: xenial
    sudo: required
    before_install:
    - sudo apt-get install -y libx11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev
      libcups2-dev libasound2
    - sudo ln -s /usr/lib/x86_64-linux-gnu/libasound.so.2 /usr/lib/x86_64-linux-gnu/libasound.so
  - os: windows
    env: OS_BUILD=windows
    before_install:
    - choco install cygwin
    - C:\\tools\\cygwin\\cygwinsetup.exe -q -P make,unzip,automake,autoconf,zip
before_script:
  - if [[ $OS_BUILD == "windows" ]]; then
      git config --system core.longpaths true;
      git config --global core.autocrlf false;
    fi
  - unset -v _JAVA_OPTIONS;
  - git clone --depth 1 https://github.com/TravaOpenJDK/openjdk-build.git;
script:
  - export JDK_BOOT_DIR="$PWD/openjdk-build/jdk-10"
  - export HSWAP_AGENT_DOWNLOAD_URL=https://github.com/HotswapProjects/HotswapAgent/releases/download/1.3.1-SNAPSHOT/hotswap-agent-1.3.1-SNAPSHOT.jar
  - mkdir -p "$JDK_BOOT_DIR"
  - if [[ $OS_BUILD == "linux" ]]; then
      wget -q -O - "https://api.adoptopenjdk.net/v2/binary/releases/openjdk10?os=linux&release=latest&arch=x64" | tar xpzf - --strip-components=2 -C ${JDK_BOOT_DIR};
    fi
  - if [[ $OS_BUILD == "osx" ]]; then
      wget -q -O - 'https://api.adoptopenjdk.net/v2/binary/releases/openjdk10?os=mac&release=latest' | tar xpzf - --strip-components=2 -C ${JDK_BOOT_DIR};
    fi
  - if [[ $OS_BUILD == "linux" || $OS_BUILD == "osx" ]]; then
      bash -c "cd openjdk-build && export LOG=info && ./makejdk-any-platform.sh --tag \"${SOURCE_JDK_TAG}\" --build-variant dcevm --branch dcevm11 --disable-test-image
        --jdk-boot-dir ${JDK_BOOT_DIR} --hswap-agent-download-url \"${HSWAP_AGENT_DOWNLOAD_URL}\" --configure-args '-disable-warnings-as-errors' 
        --target-file-name java11-openjdk-dcevm-${TRAVIS_OS_NAME}.tar.gz jdk11u";
    fi
  - if [[ $OS_BUILD == "windows" ]]; then
      powershell -Command "C:\tools\cygwin\bin\bash.exe -c './build_windows.sh'";
    fi
deploy:
  provider: releases
  api_key:
    secure: $API_KEY
  file_glob: true
  file: openjdk-build/workspace/target/*
  skip_cleanup: true
  on:
    repo: n9x0n/trava-jdk-11-dcevm
    all_branches: true
    tags: true
